### ISSUE TITLE
Please tag new version

### ISSUE THREAD

**Issue by yubiuser** [mjaschen/urlwatch-docker#17]
Please tag a new version including your fix: https://github.com/mjaschen/urlwatch-docker/commit/59382f6076ce53814c6fcdb7c191eeaf60719ed6

Currently that `latest`image on ghcr is pointing to the broken image.

https://github.com/mjaschen/urlwatch-docker/pkgs/container/urlwatch

Without tag new tag, `latest` won't be applied to the new images.

**Comment by mjaschen** [comment]
Sorry, totally missed that. I've tagged 1.2.1, pulling `latest` should give the fixed version.
